apiVersion: v1
kind: Service
metadata:
  name: ai-devops-service
  labels:
    app: ai-devops
spec:
  type: ClusterIP
  selector:
    app: ai-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
